import './globals.css';
import { Mulish } from 'next/font/google';

const mulish = Mulish({ weight: ['800', '300', '500', '900', '700'], subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={mulish.className}>{children}</body>
    </html>
  );
}
