'use client';
import './globals.css';
import { mulish } from '../components/resource';
import Navbar from '@/components/Navabar';
import Footer from '@/components/Footer';
import ReduxProvider from '@/redux/provider/ReduxProvider';
import { SessionProvider } from 'next-auth/react';
import { usePathname } from 'next/navigation';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
  sesion,
}: {
  children: React.ReactNode;
  sesion: any;
}) {
  const path = usePathname();
  console.log(path);
  return (
    <html lang="en">
      <SessionProvider session={sesion}>
        <ReduxProvider>
          <body className={`${mulish.className} min-h-screen flex flex-col`}>
            {path === '/def' ? (
              children
            ) : (
              <>
                <Navbar />
                {children}
                <Footer />
              </>
            )}
          </body>
        </ReduxProvider>
      </SessionProvider>
    </html>
  );
}
