import './globals.css';
import { mulish } from '../components/resource';
import Navbar from '@/components/Navabar';
import Footer from '@/components/Footer';
import ReduxProvider from '@/redux/provider/ReduxProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${mulish.className} min-h-screen flex flex-col`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
