// import { AiOutlineMan, AiOutlineWoman } from 'react-icons/ai';
// import { BsEmojiSmile } from 'react-icons/bs';
// import { IPerros } from './interface/IPerros.interface';
// const male = <AiOutlineMan />;
// const female = <AiOutlineWoman />;
// const friendly = <BsEmojiSmile />;

// export const perros: IPerros[] = [
//   {
//     name: 'Ramon',
//     gender: 'Macho',
//     genderI: male,
//     size: 'mediano',
//     temperament: friendly,
//     weight: 0.5,
//     age: 2,
//     country: 'Argentina',
//     location: 'Buenos Aires',
//     image: '/img/ramon.jpg',
//   },
//   {
//     name: 'Angela',
//     gender: 'Hembra',
//     genderI: female,
//     size: 'Grande',
//     temperament: friendly,
//     weight: 5,
//     age: 10,
//     country: 'Peru',
//     location: 'Lima',
//     image: '/img/tom.jpg',
//   },
//   {
//     name: 'ramon',
//     gender: 'Macho',
//     genderI: male,
//     size: 'pequeño',
//     weight: 0.5,
//     temperament: friendly,
//     age: 2,
//     country: 'Mexico',
//     location: 'Centro de mexico',
//     image: '/img/ramon.jpg',
//   },
//   {
//     name: 'rico',
//     gender: 'Hembra',
//     genderI: female,
//     size: 'mediano',
//     weight: 0.5,
//     temperament: friendly,
//     age: 2,
//     country: 'Argentina',
//     location: 'Buenos Aires',
//     image: '/img/rico.jpg',
//   },
//   {
//     name: 'tom',
//     gender: 'Macho',
//     genderI: male,
//     size: 'mediano',
//     weight: 0.5,
//     temperament: friendly,
//     age: 2,
//     country: 'Argentina',
//     location: 'Buenos Aires',
//     image: '/img/tom.jpg',
//   },
//   {
//     name: 'rico',
//     gender: 'Macho',
//     genderI: male,
//     size: 'mediano',
//     weight: 0.5,
//     temperament: friendly,
//     age: 2,
//     country: 'Argentina',
//     location: 'Buenos Aires',
//     image: '/img/rico.jpg',
//   },
// ];
